[package]
name = "rust-atomics-and-locks"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
atomic-wait = "1.0.1"

[target.'cfg(target_os = "linux")'.dependencies]
libc = "0.2.138"
